version: "3.9"

services:
  wbb:
    container_name: "${CONTAINER_NAME:-wbb-${USER}}"
    image: registry.robotics-lab.ru/wbb:0.1.0
    stdin_open: true
    privileged: true
    tty: true
    build:
      dockerfile: Dockerfile
      context: .
      tags:
        - "registry.robotics-lab.ru/wbb:latest"
        - "registry.robotics-lab.ru/wbb:0.1.0"
      x-bake:
        platforms: [linux/arm64/v8, linux/amd64]
        cache-to: "type=registry,ref=registry.robotics-lab.ru/wbb:cache,mode=max"
        cache-from: "type=registry,ref=registry.robotics-lab.ru/wbb:cache"
    ports:
      - "${FOXGLOVE_PORT:-9090}:9090"
    volumes:
      - "${PWD}:/wbb"
      - "/dev:/dev"

networks:
  default:
    name: "${CONTAINER_NAME:-wbb-${USER}}"
